# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cfaf4a683166394c809fcf35384bf392f1b710339d227501e0fea2836dbf6c77892ff58d3b91ea46bb25e186ed7c0f374fcfdffc376699828c8a2a924ca649d

test:
  secret_key_base: 7872449c3529da729ca8632ee0f4c05814c4a7b357d4452c7e512a64c067e25ff03522975b8e5b8d56e31b09ceda66f9b550354c8d6c6f21084f41bf4ecbc63b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
